version: "3.3"

services:
  mysql-server:
    container_name: zoo-mysql-server
    image: mysql:latest
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=D@TiGoNachukam2345
    #volumes:
     # - zoo-mysql-server:/var/lib/mysql
    ports:
      - "3306:3306"

  zoo-store:
    image: zoostore
    depends_on:
      - mysql-server
    restart: on-failure
    ports:
      - "1234:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
           "spring.datasource.url":"jdbc:mysql://localhost:3306/zoostore?createDatabaseIfNotExist=true",
           "spring.datasource.username":"root",
           "spring.datasource.password":"D@TiGoNachukam2345",
           "spring.jpa.database-platform":"org.hibernate.dialect.MySQLDialect",
           "spring.datasource.driver-class-name":"com.mysql.cj.jdbc.Driver",
           "spring.jpa.hibernate.ddl-auto":"update",
           "pagination":"5"
         }'

  zoo-storage:
    image: storage
    depends_on:
      - mysql-server
      - zoo-store
    restart: on-failure
    ports:
      - "1235:8081"
    environment:
      SPRING_APPLICATION_JSON: '{
           "spring.datasource.url":"jdbc:mysql://localhost:3306/storage?createDatabaseIfNotExist=true",
           "spring.datasource.username":"root",
           "spring.datasource.password":"D@TiGoNachukam2345",
           "spring.jpa.database-platform":"org.hibernate.dialect.MySQLDialect",
           "spring.datasource.driver-class-name":"com.mysql.cj.jdbc.Driver",
           "spring.jpa.hibernate.ddl-auto":"update"
         }'


  zoo-bff:
    image: bff
    depends_on:
      - mysql-server
      - zoo-store
      - zoo-storage
    restart: on-failure
    ports:
      - "1236:8082"
    environment:
      SPRING_APPLICATION_JSON: '{
           "spring.datasource.url":"jdbc:mysql://localhost:3306/bff?createDatabaseIfNotExist=true",
           "spring.datasource.username":"root",
           "spring.datasource.password":"D@TiGoNachukam2345",
           "spring.jpa.database-platform":"org.hibernate.dialect.MySQLDialect",
           "spring.datasource.driver-class-name":"com.mysql.cj.jdbc.Driver",
           "spring.jpa.hibernate.ddl-auto":"update"
         }'

#volumes:
 # zoo-mysql-server: